apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec: 
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mysql
        name: db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Ab12345*
        - name: MYSQL_DATABASE
          value: todolist
  replicas: 1
  selector:
    matchLabels:
      app: db