apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec: 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: angelogbiel/todolist-frontend:latest
          name: frontend
  replicas: 6
  selector:
    matchLabels:
      app: frontend