apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: backend