apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31000
  selector:
    app: frontend