apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32100
  selector:
    app: phpmyadmin